### ISSUE TITLE
Live demo's "Fork me on Github" link obscures the diagram

### ISSUE THREAD

**Issue by vi** [lukaslueg/macro_railroad#6]
![screenshot](https://user-images.githubusercontent.com/173219/44007058-498927fe-9e97-11e8-8cdf-0755ad49cc05.png)

At least on Chromium 67.

It should probably be somewhere above.

**Comment by bjorn3** [comment]
Same on firefox developer edition 62.0b16

**Comment by lukaslueg** [comment]
Thanks, should be fixed now. I've uploaded the whole demo [here](https://github.com/lukaslueg/macro_railroad_wasm), any pull-request would be welcome :-)
